Add some funcs to dwmc

diff --git a/dwmc b/dwmc
--- a/dwmc
+++ b/dwmc
@@ -1,7 +1,7 @@
 #!/usr/bin/env sh
 
 signal() {
-	xsetroot -name "fsignal:$*"
+  xsetroot -name "fsignal:$*"
 }
 
 usage() {
@@ -36,6 +36,7 @@ usage() {
     setlayoutex [0-n]       Set layout where layout [n] corresponds
                             to your layout array.
     shiftview +|-n          Shift view to relative tag.
+    shifttag  +|-n          Shift client to right or left tag respectively.
     focusstack [0-n]        Focus [n] client in the stack.
     incnmaster +|-n         Increase or decrease number of masters.
     focusmon +|-n           Focus monitor relative to the current
@@ -48,46 +49,50 @@ usage() {
                             monitor 0 is monitor 0 even if you are on 0.
     pushstack +|-n          Move focused client to position in stack.
                             0 = first position, -1 = last position, etc.
+    cyclelayout +|-n        Cycle up or down layout stack.
 HEREDOC
 }
 
 case $# in
-1)
-	case $1 in
-    -h | --help)
-      usage
-      exit 1
-      ;;
-    setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit | togglesticky | togglefullscr)
-      signal $1
-      ;;
-    *)
-      echo "Unknown command or missing one argument."
-      usage
-      exit 1
-      ;;
-	esac
-	;;
-2)
-	case $1 in
-    -h | --help)
-      usage
-      exit 1
-      ;;
-    view)
-      signal $1 ui $2
-      ;;
-    viewex | toggleviewex | tagex | toggletagex | setlayoutex | focusstack | incnmaster | focusmon | tagmon | focusnmon | tagnmon | pushstack | shiftview)
-      signal $1 i $2
-      ;;
-    setmfact)
-      signal $1 f $2
-      ;;
-    *)
-      echo "Unknown command or one too many arguments."
-      usage
-      exit 1
-      ;;
+  1)
+    case $1 in
+      -h | --help)
+        usage
+        exit 1
+        ;;
+      setlayout | view | viewall | togglebar | togglefloating | \
+        zoom | killclient | quit | togglesticky | togglefullscr)
+        signal $1
+        ;;
+      *)
+        echo "Unknown command or missing one argument."
+        usage
+        exit 1
+        ;;
+    esac
+    ;;
+  2)
+    case $1 in
+      -h | --help)
+        usage
+        exit 1
+        ;;
+      view)
+        signal $1 ui $2
+        ;;
+      viewex | toggleviewex | tagex | toggletagex | setlayoutex | \
+        focusstack | incnmaster | focusmon | tagmon | focusnmon | \
+        tagnmon | pushstack | shiftview | shifttag | cyclelayout)
+        signal $1 i $2
+        ;;
+      setmfact)
+        signal $1 f $2
+        ;;
+      *)
+        echo "Unknown command or one too many arguments."
+        usage
+        exit 1
+        ;;
     esac
     ;;
   *)
